#!/bin/bash
# chmod 700 RunChaste
echo 'Collect Results'
python BifucationCharacteristicParameterSet.py -Area $1 -Dil $2 -Shear $3 -Bending $4 -input $5 -output $6 >$7
exit
    # parser.add_argument('-Area', type=str, help='Need to supply a input folder')
    # parser.add_argument('-Dil', type=str, help='Need to supply a input folder')
    # parser.add_argument('-Shear', type=str, help='Need to supply a input folder')
    # parser.add_argument('-Bending', type=str, help='Need to supply a input folder')
    # parser.add_argument('-input', type=str, help='Need to supply a output folder')
    # parser.add_argument('-output', type=str, help='Need to supply a output folder')