#!/bin/bash
# chmod 700 RunChaste
echo 'RunHemeLB'
$1 > $2
echo 'GmyUnstructuredGridReader'
$3
echo 'GenerateFlowVtus'
$4
echo 'HemeLB simulation complete' > $5
echo "HemeLB simulation complete"
exit
