#!/bin/bash
# chmod 700 RunHemeLB
echo ~/Documents/testoutput/$1HemeLBFluid/config.xml
mpirun -np 2 hemelb -in ~/Documents/testoutput/$1HemeLBFluid/config.xml > /Users/jcrawshaw/Documents/testoutput/$1HemeLBFluid/HemeLBTerminalOutput.txt
echo HemeLB has finished > ~/Documents/testoutput/$1WaitFile.txt
echo "HemeLB simulation complete"
exit